# Generated by Django 3.1.3 on 2022-02-02 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('share_text', models.TextField(verbose_name='シェアラジオ全文')),
                ('started', models.DateTimeField(verbose_name='開始日時')),
                ('ended', models.DateTimeField(verbose_name='終了日時')),
                ('overview_before', models.TextField(blank=True, null=True, verbose_name='事前告知')),
                ('overview_after', models.TextField(blank=True, null=True, verbose_name='放送内容')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiko_identifier', models.CharField(max_length=80, unique=True, verbose_name='radiko ID')),
                ('name', models.CharField(max_length=80, verbose_name='名前')),
                ('abbreviation', models.CharField(help_text='一覧に表示するための表記', max_length=20, verbose_name='略称')),
                ('formatted_name', models.TextField(blank=True, null=True, verbose_name='整形した名前')),
                ('site_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='サイトURL')),
                ('wikipedia_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='Wikipedia')),
                ('address', models.CharField(max_length=400, verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名前')),
                ('formatted_name', models.TextField(blank=True, null=True, verbose_name='整形した名前')),
                ('twitter_screen_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Twitterスクリーンネーム')),
                ('site_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='サイトURL')),
                ('wikipedia_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='Wikipedia')),
                ('key_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airs.broadcaster', verbose_name='キー局')),
            ],
        ),
        migrations.CreateModel(
            name='Nanitozo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.BooleanField(default=False, verbose_name='満足')),
                ('comment_open', models.BooleanField(default=True, verbose_name='コメント公開')),
                ('comment_recommend', models.TextField(blank=True, null=True, verbose_name='推薦文')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='感想文')),
                ('comment_negative', models.TextField(blank=True, null=True, verbose_name='感想文ネガ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airs.air', verbose_name='放送')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='リスナー')),
            ],
        ),
        migrations.AddField(
            model_name='air',
            name='broadcaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airs.broadcaster', verbose_name='放送局'),
        ),
        migrations.AddField(
            model_name='air',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airs.program', verbose_name='番組'),
        ),
        migrations.AddConstraint(
            model_name='nanitozo',
            constraint=models.UniqueConstraint(fields=('air', 'user'), name='nanitozo_unique'),
        ),
        migrations.AddConstraint(
            model_name='air',
            constraint=models.UniqueConstraint(fields=('broadcaster', 'started'), name='air_unique'),
        ),
    ]
