# Generated by Django 3.1.3 on 2021-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='ended',
            field=models.DateTimeField(verbose_name='終了日時'),
        ),
        migrations.AlterField(
            model_name='air',
            name='started',
            field=models.DateTimeField(verbose_name='開始日時'),
        ),
    ]
