"""
Django settings for rnsite project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import logging.config
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent # 初期値
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Herokuデプロイ時に追加


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# Railway環境での適切なALLOWED_HOSTS設定
def get_allowed_hosts():
    """
    Railway環境での動的ALLOWED_HOSTS設定
    独自ドメイン対応、複数ドメイン対応、Railwayヘルスチェック対応
    """
    allowed_hosts = []
    
    # 1. カスタムドメイン設定（独自ドメイン用）
    custom_domain = os.getenv('CUSTOM_DOMAIN', '')
    if custom_domain:
        allowed_hosts.append(custom_domain)
    
    # 2. Railway自動設定ドメイン
    railway_static_url = os.getenv('RAILWAY_STATIC_URL', '')
    if railway_static_url:
        from urllib.parse import urlparse
        parsed_url = urlparse(railway_static_url)
        if parsed_url.netloc and parsed_url.netloc not in allowed_hosts:
            allowed_hosts.append(parsed_url.netloc)
    
    # 3. Railway公式ドメイン（フォールバック）
    railway_public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
    if railway_public_domain and railway_public_domain not in allowed_hosts:
        allowed_hosts.append(railway_public_domain)
    
    # 4. ローカル開発環境
    if not allowed_hosts:
        allowed_hosts = ['localhost', '127.0.0.1', '[::1]']
    
    return allowed_hosts

ALLOWED_HOSTS = get_allowed_hosts()

# Application definition

INSTALLED_APPS = [
    'airs.apps.AirsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'airs.templatetags.air_nanitozo',
    'airs.templatetags.rn_datetime',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'airs.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'rnsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'air_nanitozo': 'airs.templatetags.air_nanitozo',
                'rn_datetime': 'airs.templatetags.rn_datetime',
            }
        },
    },
]

WSGI_APPLICATION = 'rnsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ログ設定はDEBUG定義後に移動


# login、logoutのリダイレクト先をカスタマイズ
LOGIN_REDIRECT_URL = 'airs:index'
LOGOUT_REDIRECT_URL = 'airs:index'

# ログインセッションの有効期限
# SESSION_COOKIE_AGE = 1209600 # デフォルトの2週間
SESSION_SAVE_EVERY_REQUEST = True  # これを追加したら随時延長


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# 静的ファイルの検索パス
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'airs/static'),
]

# Railway環境での静的ファイル設定
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# WhiteNoise設定
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True



DEBUG = False

try:
    from local_settings import *
except ImportError:
    pass

# ログ設定（DEBUG定義後）
LOGGING_CONFIG = None
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'development': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
        'production': {
            'format': '%(asctime)s [%(levelname)s] %(name)s.%(funcName)s:%(lineno)d - %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'production' if not DEBUG else 'development',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'airs': {
            'handlers': ['console'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        'share_text': {
            'handlers': ['console'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
    },
}
logging.config.dictConfig(LOGGING)

if not DEBUG:
    SECRET_KEY = os.getenv('SECRET_KEY')
    
    # 本番環境での静的ファイル設定
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    
    # セキュリティ設定の強化
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HTTPS強制設定（Railway環境では自動でHTTPSが有効）
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Sentry設定（任意）
    if os.getenv('SENTRY_DSN'):
        sentry_sdk.init(
            dsn=os.getenv('SENTRY_DSN'),
            integrations=[
                DjangoIntegration(),
            ],
            traces_sample_rate=1.0,
            send_default_pii=True
        )
